### ISSUE TITLE
Debugging 결과물의 색깔이 모두 동일하여 눈에 잘 들어오지 않습니다.

### ISSUE THREAD

**Issue by JINSUBY** [20-2-SKKU-OSS/PySnooper-8#7]
Debugging 결과물의 색깔이 모두 동일하여 눈에 잘 들어오지 않습니다.
각 기능별로 다른 색상으로 표기한다던가, notation을 다르게 주는식으로 눈에 확 튀게 나오는게 어떨까요?
다른 아이디어 있으시면 말씀해주시길 바랍니다.

**Comment by CheonKiO** [comment]
색상을 다르게 바꿀 수 있다면 확실히 가독성이 더 좋을것 같습니다

**Comment by xhdzl6280** [comment]
저도 출력물이 가독성이 떨어진다는 생각을 했습니다. 시간과 코드 내용을 구분할 수 있게 수정이 되면 좋을 것 같아요

**Comment by YangSejung** [comment]
출력되는 결과물의 종류마다 (시간, 변수, return 값 등) 색깔이 다르면 더 가독성이 높아질 것 같아요

**Comment by hojin915** [comment]
variable과 나머지만 구분하는게 좋지 않을까 싶습니다. 색이 너무 많아지면 오히려 가독성이 안좋아질수도 있다는 개인적인 생각

**Comment by yunminjin2** [comment]
> variable과 나머지만 구분하는게 좋지 않을까 싶습니다. 색이 너무 많아지면 오히려 가독성이 안좋아질수도 있다는 개인적인 생각

동의합니다. 너무 화려하면 눈에 잘 안들어올 것 같습니다.

**Comment by JINSUBY** [comment]
> variable과 나머지만 구분하는게 좋지 않을까 싶습니다. 색이 너무 많아지면 오히려 가독성이 안좋아질수도 있다는 개인적인 생각

시간, 코드내용, variable과 나머지 부분 들을 고려하여 색상을 변경해보아야겠군요...

**Comment by yunminjin2** [comment]
작성하신 결과물에 exception 색깔 출력 기능이 빠져있는 것을 보았습니다. 혹시 의도하신 건가요 아니면, 실수로 추가가 안된건가요??  추가가 안된거면 제가 구현해놓도록 하겠습니다.

**Comment by JINSUBY** [comment]
> 작성하신 결과물에 exception 색깔 출력 기능이 빠져있는 것을 보았습니다. 혹시 의도하신 건가요 아니면, 실수로 추가가 안된건가요?? 추가가 안된거면 제가 구현해놓도록 하겠습니다.

아 제가 놓친 부분이 있었습니다. 수정해주시면 감사하겠습니다.

**Comment by yunminjin2** [comment]
> > 작성하신 결과물에 exception 색깔 출력 기능이 빠져있는 것을 보았습니다. 혹시 의도하신 건가요 아니면, 실수로 추가가 안된건가요?? 추가가 안된거면 제가 구현해놓도록 하겠습니다.
> 
> 아 제가 놓친 부분이 있었습니다. 수정해주시면 감사하겠습니다.

수정해서 올렸습니다.
