### ISSUE TITLE
색깔 출력 관련해서 개발자분의 대답

### ISSUE THREAD

**Issue by yunminjin2** [20-2-SKKU-OSS/PySnooper-8#8]
특정 줄이 Elapsed time 쪽이 작동하지 않는다라고 답주셔서 그 부분에 색깔 넣는 코드를 빼야할 것 같습니다.
또한, 각 개발자마다 터미널 환경이 다르기 때문에, 색깔 추가 기능은 선택적으로 작동해야 한다고 답주셨습니다. 

일단 Base는 색깔 안넣는 방향으로 코드를 수정하고, 사용자가 snoop()에 변수 추가하면 거기에 맞춰서 색깔을 추가하도록 바꾸는 게 좋을 것 같습니다.

**Comment by JINSUBY** [comment]
터미널 환경이 달라서 생기는 문제점 같은 경우는 코드의 low한 라이브러리들을 건들여야 될 것같아서..
변수 하나 설정해서 선택적으로 색깔을 받아보이는게 좋아보이긴 합니다.

**Comment by yunminjin2** [comment]
참고하여 새로운 코드 작성했습니다. 하지만, 아직 코드적인 완성도가 높지 않아서, 조금 다듬어야 할 필요가 있을 것 같습니다.
