### ISSUE TITLE
정적 페이지에 정리

### ISSUE THREAD

**Issue by xhdzl6280** [20-2-SKKU-OSS/PySnooper-8#9]
논의한 부분 정적페이지에 어떤 식으로 정리하면 좋을까요?

**Comment by JINSUBY** [comment]
공지사항 내용 중 "두가지 이상 프로젝트를 하셔도 상관없으나 프로젝트 진행 및 완성도가 떨어지면 한개만 진행한것보다 좋지 않을것 같습니다" 이런 내용이 있기에 우선적으로 Pysnooper를 선정하게 된 이유에 대한 포스트틑 정리해야 할 것 같습니다.

**Comment by yunminjin2** [comment]
일단 저희가 한 풀리퀘 위주로 분석을 해서 포스터로 올리면 좋을 것 같습니다.

**Comment by hojin915** [comment]
이슈랑 풀리퀘스트를 링크나 캡처해서 사용하면 좋을것같아요. 캡처한거는 표지 이미지로도 사용할 수 있을수도?

**Comment by CheonKiO** [comment]
프로젝트 결과물을 전후로 캡쳐해서 변화를 보여주는 것도 좋을 것 같습니다.
